// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssigmaapi/type/useractivity.proto

package useractivity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserActivity_UserState int32

const (
	UserActivity_WORKING UserActivity_UserState = 0
	UserActivity_AWAY    UserActivity_UserState = 1
)

var UserActivity_UserState_name = map[int32]string{
	0: "WORKING",
	1: "AWAY",
}

var UserActivity_UserState_value = map[string]int32{
	"WORKING": 0,
	"AWAY":    1,
}

func (x UserActivity_UserState) String() string {
	return proto.EnumName(UserActivity_UserState_name, int32(x))
}

func (UserActivity_UserState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ab6ae77cd34cfb8, []int{0, 0}
}

type ApplicationWindow_WindowState int32

const (
	ApplicationWindow_NORMAL    ApplicationWindow_WindowState = 0
	ApplicationWindow_MAXIMIZED ApplicationWindow_WindowState = 1
	ApplicationWindow_MINIMIZED ApplicationWindow_WindowState = 2
)

var ApplicationWindow_WindowState_name = map[int32]string{
	0: "NORMAL",
	1: "MAXIMIZED",
	2: "MINIMIZED",
}

var ApplicationWindow_WindowState_value = map[string]int32{
	"NORMAL":    0,
	"MAXIMIZED": 1,
	"MINIMIZED": 2,
}

func (x ApplicationWindow_WindowState) String() string {
	return proto.EnumName(ApplicationWindow_WindowState_name, int32(x))
}

func (ApplicationWindow_WindowState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ab6ae77cd34cfb8, []int{3, 0}
}

type UserActivity struct {
	StartTimestamp       int64                  `protobuf:"varint,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp         int64                  `protobuf:"varint,2,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	KeyboardInput        *KeyboardInput         `protobuf:"bytes,3,opt,name=keyboard_input,json=keyboardInput,proto3" json:"keyboard_input,omitempty"`
	WindowList           []*ApplicationWindow   `protobuf:"bytes,4,rep,name=window_list,json=windowList,proto3" json:"window_list,omitempty"`
	UserState            UserActivity_UserState `protobuf:"varint,5,opt,name=user_state,json=userState,proto3,enum=ssigmaapi.type.UserActivity_UserState" json:"user_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserActivity) Reset()         { *m = UserActivity{} }
func (m *UserActivity) String() string { return proto.CompactTextString(m) }
func (*UserActivity) ProtoMessage()    {}
func (*UserActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab6ae77cd34cfb8, []int{0}
}

func (m *UserActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActivity.Unmarshal(m, b)
}
func (m *UserActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActivity.Marshal(b, m, deterministic)
}
func (m *UserActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActivity.Merge(m, src)
}
func (m *UserActivity) XXX_Size() int {
	return xxx_messageInfo_UserActivity.Size(m)
}
func (m *UserActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActivity.DiscardUnknown(m)
}

var xxx_messageInfo_UserActivity proto.InternalMessageInfo

func (m *UserActivity) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *UserActivity) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *UserActivity) GetKeyboardInput() *KeyboardInput {
	if m != nil {
		return m.KeyboardInput
	}
	return nil
}

func (m *UserActivity) GetWindowList() []*ApplicationWindow {
	if m != nil {
		return m.WindowList
	}
	return nil
}

func (m *UserActivity) GetUserState() UserActivity_UserState {
	if m != nil {
		return m.UserState
	}
	return UserActivity_WORKING
}

type KeyboardInput struct {
	StrokeCount          int64    `protobuf:"varint,1,opt,name=stroke_count,json=strokeCount,proto3" json:"stroke_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyboardInput) Reset()         { *m = KeyboardInput{} }
func (m *KeyboardInput) String() string { return proto.CompactTextString(m) }
func (*KeyboardInput) ProtoMessage()    {}
func (*KeyboardInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab6ae77cd34cfb8, []int{1}
}

func (m *KeyboardInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyboardInput.Unmarshal(m, b)
}
func (m *KeyboardInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyboardInput.Marshal(b, m, deterministic)
}
func (m *KeyboardInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyboardInput.Merge(m, src)
}
func (m *KeyboardInput) XXX_Size() int {
	return xxx_messageInfo_KeyboardInput.Size(m)
}
func (m *KeyboardInput) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyboardInput.DiscardUnknown(m)
}

var xxx_messageInfo_KeyboardInput proto.InternalMessageInfo

func (m *KeyboardInput) GetStrokeCount() int64 {
	if m != nil {
		return m.StrokeCount
	}
	return 0
}

type Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab6ae77cd34cfb8, []int{2}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type ApplicationWindow struct {
	Lefttop              *Point                        `protobuf:"bytes,1,opt,name=lefttop,proto3" json:"lefttop,omitempty"`
	Height               int64                         `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64                         `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Title                string                        `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ProgramName          string                        `protobuf:"bytes,5,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	Description          string                        `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Company              string                        `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	IsForeground         bool                          `protobuf:"varint,8,opt,name=is_foreground,json=isForeground,proto3" json:"is_foreground,omitempty"`
	WindowState          ApplicationWindow_WindowState `protobuf:"varint,9,opt,name=window_state,json=windowState,proto3,enum=ssigmaapi.type.ApplicationWindow_WindowState" json:"window_state,omitempty"`
	Timestamp            int64                         `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ApplicationWindow) Reset()         { *m = ApplicationWindow{} }
func (m *ApplicationWindow) String() string { return proto.CompactTextString(m) }
func (*ApplicationWindow) ProtoMessage()    {}
func (*ApplicationWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ab6ae77cd34cfb8, []int{3}
}

func (m *ApplicationWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationWindow.Unmarshal(m, b)
}
func (m *ApplicationWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationWindow.Marshal(b, m, deterministic)
}
func (m *ApplicationWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationWindow.Merge(m, src)
}
func (m *ApplicationWindow) XXX_Size() int {
	return xxx_messageInfo_ApplicationWindow.Size(m)
}
func (m *ApplicationWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationWindow.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationWindow proto.InternalMessageInfo

func (m *ApplicationWindow) GetLefttop() *Point {
	if m != nil {
		return m.Lefttop
	}
	return nil
}

func (m *ApplicationWindow) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ApplicationWindow) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ApplicationWindow) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ApplicationWindow) GetProgramName() string {
	if m != nil {
		return m.ProgramName
	}
	return ""
}

func (m *ApplicationWindow) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ApplicationWindow) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *ApplicationWindow) GetIsForeground() bool {
	if m != nil {
		return m.IsForeground
	}
	return false
}

func (m *ApplicationWindow) GetWindowState() ApplicationWindow_WindowState {
	if m != nil {
		return m.WindowState
	}
	return ApplicationWindow_NORMAL
}

func (m *ApplicationWindow) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("ssigmaapi.type.UserActivity_UserState", UserActivity_UserState_name, UserActivity_UserState_value)
	proto.RegisterEnum("ssigmaapi.type.ApplicationWindow_WindowState", ApplicationWindow_WindowState_name, ApplicationWindow_WindowState_value)
	proto.RegisterType((*UserActivity)(nil), "ssigmaapi.type.UserActivity")
	proto.RegisterType((*KeyboardInput)(nil), "ssigmaapi.type.KeyboardInput")
	proto.RegisterType((*Point)(nil), "ssigmaapi.type.Point")
	proto.RegisterType((*ApplicationWindow)(nil), "ssigmaapi.type.ApplicationWindow")
}

func init() { proto.RegisterFile("ssigmaapi/type/useractivity.proto", fileDescriptor_0ab6ae77cd34cfb8) }

var fileDescriptor_0ab6ae77cd34cfb8 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xa6, 0x4d, 0xea, 0xb1, 0x13, 0xc2, 0x0a, 0x90, 0x0f, 0x20, 0xb9, 0xae, 0x04,
	0xbe, 0xe0, 0x48, 0xe6, 0xc0, 0x01, 0x84, 0xe4, 0xd2, 0x82, 0xa2, 0xb6, 0x69, 0x65, 0x40, 0x85,
	0x5e, 0xac, 0xad, 0xbd, 0x75, 0x56, 0x89, 0xbd, 0x96, 0x77, 0x4c, 0xeb, 0x07, 0xe3, 0x41, 0x78,
	0x23, 0xe4, 0x3f, 0x49, 0xdd, 0xf4, 0xc0, 0x29, 0xf9, 0x3e, 0xff, 0x76, 0xb4, 0x33, 0xdf, 0x2c,
	0xec, 0x4b, 0xc9, 0xe3, 0x84, 0xd2, 0x8c, 0x4f, 0xb0, 0xcc, 0xd8, 0xa4, 0x90, 0x2c, 0xa7, 0x21,
	0xf2, 0xdf, 0x1c, 0x4b, 0x27, 0xcb, 0x05, 0x0a, 0x32, 0x5a, 0x23, 0x4e, 0x85, 0x58, 0x7f, 0xb7,
	0x41, 0xff, 0x21, 0x59, 0xee, 0xb5, 0x18, 0x79, 0x03, 0x4f, 0x24, 0xd2, 0x1c, 0x03, 0xe4, 0x09,
	0x93, 0x48, 0x93, 0xcc, 0x50, 0x4c, 0xc5, 0xee, 0xf9, 0xa3, 0xda, 0xfe, 0xbe, 0x72, 0xc9, 0x01,
	0x0c, 0x59, 0x1a, 0x75, 0xb0, 0xed, 0x1a, 0xd3, 0x59, 0x1a, 0xdd, 0x43, 0x47, 0x30, 0x5a, 0xb0,
	0xf2, 0x5a, 0xd0, 0x3c, 0x0a, 0x78, 0x9a, 0x15, 0x68, 0xf4, 0x4c, 0xc5, 0xd6, 0xdc, 0x57, 0xce,
	0xc3, 0x7b, 0x38, 0x27, 0x2d, 0x35, 0xad, 0x20, 0x7f, 0xb8, 0xe8, 0x4a, 0x72, 0x08, 0xda, 0x2d,
	0x4f, 0x23, 0x71, 0x1b, 0x2c, 0xb9, 0x44, 0x63, 0xc7, 0xec, 0xd9, 0x9a, 0xbb, 0xbf, 0x59, 0xc2,
	0xcb, 0xb2, 0x25, 0x0f, 0x29, 0x72, 0x91, 0x5e, 0xd6, 0xb4, 0x0f, 0xcd, 0xa9, 0x53, 0x2e, 0x91,
	0x1c, 0x03, 0x54, 0xe3, 0x08, 0x24, 0x52, 0x64, 0xc6, 0xae, 0xa9, 0xd8, 0x23, 0xf7, 0xf5, 0x66,
	0x89, 0xee, 0x24, 0x6a, 0xf1, 0xad, 0xa2, 0x7d, 0xb5, 0x58, 0xfd, 0xb5, 0x2c, 0x50, 0xd7, 0x3e,
	0xd1, 0x60, 0x70, 0x79, 0xee, 0x9f, 0x4c, 0x67, 0x5f, 0xc7, 0x5b, 0x64, 0x0f, 0x76, 0xbc, 0x4b,
	0xef, 0xd7, 0x58, 0xb1, 0x5c, 0x18, 0x3e, 0x68, 0x87, 0xec, 0x83, 0x2e, 0x31, 0x17, 0x0b, 0x16,
	0x84, 0xa2, 0x48, 0xb1, 0x1d, 0xa8, 0xd6, 0x78, 0x9f, 0x2b, 0xcb, 0x3a, 0x80, 0xdd, 0x0b, 0xc1,
	0x53, 0x24, 0x3a, 0x28, 0x77, 0x2d, 0xa0, 0xdc, 0x55, 0xaa, 0x6c, 0x07, 0xab, 0x94, 0xd6, 0x9f,
	0x1e, 0x3c, 0x7d, 0xd4, 0x25, 0x99, 0xc0, 0x60, 0xc9, 0x6e, 0x10, 0x45, 0x93, 0x94, 0xe6, 0x3e,
	0xdf, 0x6c, 0xab, 0xae, 0xec, 0xaf, 0x28, 0xf2, 0x02, 0xfa, 0x73, 0xc6, 0xe3, 0x39, 0xb6, 0x95,
	0x5b, 0x45, 0x9e, 0xc1, 0xee, 0x2d, 0x8f, 0x70, 0x5e, 0x67, 0xd4, 0xf3, 0x1b, 0x51, 0xb9, 0xc8,
	0x71, 0xc9, 0x8c, 0x1d, 0x53, 0xb1, 0x55, 0xbf, 0x11, 0x55, 0x4b, 0x59, 0x2e, 0xe2, 0x9c, 0x26,
	0x41, 0x4a, 0x93, 0x66, 0xa0, 0xaa, 0xaf, 0xb5, 0xde, 0x8c, 0x26, 0x8c, 0x98, 0xa0, 0x45, 0x4c,
	0x86, 0x39, 0xcf, 0xaa, 0xcb, 0x1a, 0xfd, 0x86, 0xe8, 0x58, 0xc4, 0x80, 0x41, 0x28, 0x92, 0x8c,
	0xa6, 0xa5, 0x31, 0xa8, 0xbf, 0xae, 0x64, 0xb5, 0x5c, 0x5c, 0x06, 0x37, 0x22, 0x67, 0x71, 0x2e,
	0x8a, 0x34, 0x32, 0xf6, 0x4c, 0xc5, 0xde, 0xf3, 0x75, 0x2e, 0xbf, 0xac, 0x3d, 0x72, 0x01, 0x7a,
	0xbb, 0x16, 0x4d, 0xa8, 0x6a, 0x1d, 0xea, 0xdb, 0xff, 0xee, 0x85, 0xd3, 0xfc, 0x34, 0xd9, 0xb6,
	0x9b, 0xd5, 0x04, 0xfa, 0x12, 0xd4, 0xfb, 0x7d, 0x86, 0x7a, 0x0a, 0xf7, 0x86, 0xf5, 0x1e, 0xb4,
	0xce, 0x49, 0x02, 0xd0, 0x9f, 0x9d, 0xfb, 0x67, 0xde, 0xe9, 0x78, 0x8b, 0x0c, 0x41, 0x3d, 0xf3,
	0x7e, 0x4e, 0xcf, 0xa6, 0x57, 0xc7, 0x47, 0x63, 0xa5, 0x96, 0xd3, 0x59, 0x2b, 0xb7, 0x0f, 0x3f,
	0x5d, 0x7d, 0x8c, 0x39, 0xce, 0x8b, 0x6b, 0x27, 0x14, 0xc9, 0x64, 0x41, 0x39, 0x0a, 0x77, 0xb2,
	0xbe, 0x65, 0x2c, 0x1e, 0xbf, 0xd6, 0x0f, 0x5d, 0x71, 0xdd, 0xaf, 0xdf, 0xee, 0xbb, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0x26, 0x7d, 0xad, 0xe0, 0x03, 0x00, 0x00,
}
