// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssigmaapi/type/hoge.proto

package hoge

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hoge struct {
	Huga                 string   `protobuf:"bytes,1,opt,name=huga,proto3" json:"huga,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hoge) Reset()         { *m = Hoge{} }
func (m *Hoge) String() string { return proto.CompactTextString(m) }
func (*Hoge) ProtoMessage()    {}
func (*Hoge) Descriptor() ([]byte, []int) {
	return fileDescriptor_0df4af4b37e1c72b, []int{0}
}

func (m *Hoge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hoge.Unmarshal(m, b)
}
func (m *Hoge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hoge.Marshal(b, m, deterministic)
}
func (m *Hoge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hoge.Merge(m, src)
}
func (m *Hoge) XXX_Size() int {
	return xxx_messageInfo_Hoge.Size(m)
}
func (m *Hoge) XXX_DiscardUnknown() {
	xxx_messageInfo_Hoge.DiscardUnknown(m)
}

var xxx_messageInfo_Hoge proto.InternalMessageInfo

func (m *Hoge) GetHuga() string {
	if m != nil {
		return m.Huga
	}
	return ""
}

func init() {
	proto.RegisterType((*Hoge)(nil), "ssigmaapi.type.Hoge")
}

func init() { proto.RegisterFile("ssigmaapi/type/hoge.proto", fileDescriptor_0df4af4b37e1c72b) }

var fileDescriptor_0df4af4b37e1c72b = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x2e, 0xce, 0x4c,
	0xcf, 0x4d, 0x4c, 0x2c, 0xc8, 0xd4, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0xcf, 0xc8, 0x4f, 0x4f, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x83, 0x4b, 0xe9, 0x81, 0xa4, 0x94, 0xa4, 0xb8, 0x58,
	0x3c, 0xf2, 0xd3, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x32, 0x4a, 0xd3, 0x13, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x27, 0xbd, 0x28, 0x9d, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd,
	0xe4, 0xfc, 0x5c, 0xfd, 0xec, 0xc4, 0xcc, 0x92, 0x7c, 0x23, 0x7d, 0xb8, 0xfe, 0xf4, 0x7c, 0x84,
	0xe1, 0xd6, 0x20, 0x22, 0x89, 0x0d, 0x6c, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x42,
	0x33, 0x40, 0x7f, 0x00, 0x00, 0x00,
}
